import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globalStyles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import Layout from '@/components/layouts/Layout'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
